"""empty message

Revision ID: 5dd6d041cf32
Revises: 
Create Date: 2022-06-19 18:32:05.950687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd6d041cf32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Descuentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('porcentaje', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Regiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('numero', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=250), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Descuentos_Productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descuento_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['descuento_id'], ['Descuentos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['Regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['Provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=250), nullable=False),
    sa.Column('apellido_materno', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('comuna_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['comuna_id'], ['Comunas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Donaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_donacion', sa.DateTime(), nullable=False),
    sa.Column('monto_donacion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_termino', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('iva', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['Vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Despachos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('hora_entrega', sa.Time(), nullable=True),
    sa.Column('rut_recibe', sa.String(length=250), nullable=True),
    sa.Column('nombre_recibe', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['Ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Detalle_Ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['Ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Detalle_Ventas')
    op.drop_table('Despachos')
    op.drop_table('Ventas')
    op.drop_table('Suscripciones')
    op.drop_table('Donaciones')
    op.drop_table('Clientes')
    op.drop_table('Comunas')
    op.drop_table('Provincias')
    op.drop_table('Descuentos_Productos')
    op.drop_table('Vendedores')
    op.drop_table('Usuario')
    op.drop_table('Regiones')
    op.drop_table('Productos')
    op.drop_table('Descuentos')
    # ### end Alembic commands ###
